// vue/barcode-scanner/src/App.vue
<script setup lang="ts">
  import { onMounted, ref } from 'vue';
  import { BarcodeReader, type TextResult } from "dynamsoft-javascript-barcode";

  BarcodeReader.engineResourcePath = "https://unpkg.com/dynamsoft-javascript-barcode@9.0.2/dist/";
  let reader:BarcodeReader;
  let scanned = false;
  let decoding = false;
  let interval:any = null;
  const continuous = ref(false);
  const cameraElement:any = ref(null);
  const active = ref(false);

  onMounted(async () => {
    BarcodeReader.license = "DLS2eyJoYW5kc2hha2VDb2RlIjoiMjAwMDAxLTE2NDk4Mjk3OTI2MzUiLCJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSIsInNlc3Npb25QYXNzd29yZCI6IndTcGR6Vm05WDJrcEQ5YUoifQ==";
    reader = await BarcodeReader.createInstance();
  })

  const startCamera = () => {
    active.value  = true;
  }

  const stopCamera = () => {
    active.value  = false;
  }

  const onOpened = () => {
    console.log("opened");
    startDecoding();
  }

  const startDecoding = () => {
    scanned = false;
    stopDecoding();
    //1000/25=40
    interval = setInterval(decode, 40);
  }

  const stopDecoding = () => {
    clearInterval(interval);
  }

  const decode = async () => {
    if (decoding === false && reader && cameraElement.value) {
      console.log("decoding");
      const video = await cameraElement.value.getVideoElement();
      decoding = true;
      try {
        let results = await reader.decode(video);
        if (results.length>0 && scanned === false && continuous.value === false) {
          scanned = true;
          stopDecoding();
          stopCamera();
          alert(results[0].barcodeText);
        }else{
          await cameraElement.value.updateAnalysingResults(wrapResults(results));
        }

      } catch (error) {
        console.log(error);
      }
      decoding = false;
    }
  }

  const wrapResults = (results:TextResult[]) => {
    let analysingResults = [];
    for (let index = 0; index < results.length; index++) {
      const result = results[index];
      let analysingResult:any = {};
      analysingResult.text = result.barcodeText;
      analysingResult.localizationResult = [
        {x:result.localizationResult.x1,y:result.localizationResult.y1},
        {x:result.localizationResult.x2,y:result.localizationResult.y2},
        {x:result.localizationResult.x3,y:result.localizationResult.y3},
        {x:result.localizationResult.x4,y:result.localizationResult.y4}
      ];
      analysingResults.push(analysingResult)
    }
    return analysingResults;
  }
</script>

<template>
  <div :style="{display: active ? 'none' : '' }">
    <button v-on:click="startCamera">Start Camera</button>
    <label>
    <input type="checkbox" v-model="continuous" />
    Continuous Scan
    </label>
  </div>
  <camera-preview 
    ref="cameraElement"
    desired-camera="founder"
    draw-overlay="true"
    v-on:opened="onOpened"
    :active="active"
    :style="{display: active ? '' : 'none' }"
  >
    <button id="close-btn" v-on:click="stopCamera">Close</button>
  </camera-preview>
</template>

<style>
  camera-preview {
    height:100%;
    width:100%;
    position: absolute;
    right:0;
    top:0;
  }

  #close-btn {
    position:absolute;
    right:0;
    top:0;
  }
</style>

// react/src/App.js
import { useRef, useState, useEffect } from 'react';
import './App.css';
import { BarcodeReader } from "dynamsoft-javascript-barcode";

BarcodeReader.engineResourcePath = "https://unpkg.com/dynamsoft-javascript-barcode@9.0.2/dist/";

function App() {
  const [active,setActive] = useState(false);
  const [continuous,setContinuous] = useState(true);
  const continuousRef = useRef(continuous);
  const decoding = useRef(false);
  const interval = useRef(null);
  const scanned = useRef(false);
  const reader = useRef(null);
  const cameraElement = useRef(null);

  const startCamera = () => {
    setActive(true);
  }

  const stopCamera = () => {
    stopDecoding();
    setActive(false);
  }

  const onOpened = () => {
    console.log("on opened");
    startDecoding();
  }

  useEffect(() => {
    const init = async () => {
      BarcodeReader.license = "DLS2eyJoYW5kc2hha2VDb2RlIjoiMjAwMDAxLTE2NDk4Mjk3OTI2MzUiLCJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSIsInNlc3Npb25QYXNzd29yZCI6IndTcGR6Vm05WDJrcEQ5YUoifQ==";
      reader.current = await BarcodeReader.createInstance();
    }
    init();
    cameraElement.current.addEventListener("opened",onOpened);
    cameraElement.current.desiredResolution = {width:1280,height:720};
  }, []);

  const startDecoding = () => {
    scanned.current = false;
    stopDecoding();
    //1000/25=40
    interval.current = setInterval(decode, 40);
  }

  const stopDecoding = () => {
    clearInterval(interval.current);
  }

  const decode = async () => {
    if (decoding.current === false && reader.current) {
      console.log("decoding");
      const video = await cameraElement.current.getVideoElement();
      decoding.current = true;
      try {
        let results = await reader.current.decode(video);
        if (results.length>0 && scanned.current === false && continuousRef.current === false) {
          scanned.current = true;
          stopDecoding();
          stopCamera();
          alert(results[0].barcodeText);
        }else{
          await cameraElement.current.updateAnalysingResults(wrapResults(results));
        }

      } catch (error) {
        console.log(error);
      }
      decoding.current = false;
    }
  }

  const wrapResults = (results) => {
    let analysingResults = [];
    for (let index = 0; index < results.length; index++) {
      const result = results[index];
      let analysingResult = {};
      analysingResult.text = result.barcodeText;
      analysingResult.localizationResult = [
        {x:result.localizationResult.x1,y:result.localizationResult.y1},
        {x:result.localizationResult.x2,y:result.localizationResult.y2},
        {x:result.localizationResult.x3,y:result.localizationResult.y3},
        {x:result.localizationResult.x4,y:result.localizationResult.y4}
      ];
      analysingResults.push(analysingResult)
    }
    return analysingResults;
  }

  const updateContinuous = (e) => {
    setContinuous(!continuous);
    continuousRef.current = !continuous;
  }

  return (
    <div>
      <camera-preview 
        ref={cameraElement}
        active={active}
        desired-camera="founder"
        draw-overlay={true}
        style={{display:active ? '' :' none'}}
      >
        <button id="close-btn" onClick={stopCamera}>Close</button>
      </camera-preview>
      <div style={{display:active ? 'none' : ''}}>
        <button onClick={startCamera} >Start Scanning</button>
        <label>
        <input
          type="checkbox"
          checked={continuous}
          onChange={updateContinuous}
        />
        Continuous Scan
        </label>
      </div>
    </div>
  );
}

export default App;
