// angular/src/app/app.component.ts
import { Component, ElementRef, Input, ViewChild } from '@angular/core';
import { BarcodeReader, TextResult } from "dynamsoft-javascript-barcode";

BarcodeReader.engineResourcePath = "https://unpkg.com/dynamsoft-javascript-barcode@9.0.2/dist/";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title:string = 'barcode-scanner';
  active:boolean = false;
  scanned:boolean = false;
  decoding:boolean = false;
  continuous:boolean = false;
  interval:any = null;
  reader!:BarcodeReader;
  @ViewChild('cameraElement') cameraElement:any;
  
  async ngOnInit() {
    BarcodeReader.license = "DLS2eyJoYW5kc2hha2VDb2RlIjoiMjAwMDAxLTE2NDk4Mjk3OTI2MzUiLCJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSIsInNlc3Npb25QYXNzd29yZCI6IndTcGR6Vm05WDJrcEQ5YUoifQ==";
    this.reader = await BarcodeReader.createInstance();
  }

  startCamera() {
    this.active = true;
  }

  stopCamera() {
    this.stopDecoding();
    this.active = false;
  }

  onOpened() {
    this.startDecoding();
  }

  startDecoding() {
    this.scanned = false;
    this.decoding = false
    this.stopDecoding();
    //1000/25=40

    const decode = async () => {
      if (this.decoding === false && this.reader != null) {
        console.log("decoding");
        const video = await this.cameraElement.nativeElement.getVideoElement();
        this.decoding = true;
        try {
          let results = await this.reader.decode(video);
          if (results.length>0 && this.scanned === false && this.continuous === false) {
            this.scanned = true;
            this.stopDecoding();
            this.stopCamera();
            alert(results[0].barcodeText);
          }else{
            await this.cameraElement.nativeElement.updateAnalysingResults(this.wrapResults(results));
          }
  
        } catch (error) {
          console.log(error);
        }
        this.decoding = false;
      }
    }

    this.interval = setInterval(decode, 40);
  }

  stopDecoding() {
    if (this.interval) {
      clearInterval(this.interval);
    }
  }

  wrapResults(results:TextResult[]) {
    let analysingResults = [];
    for (let index = 0; index < results.length; index++) {
      const result = results[index];
      let analysingResult:any = {};
      analysingResult.text = result.barcodeText;
      analysingResult.localizationResult = [
        {x:result.localizationResult.x1,y:result.localizationResult.y1},
        {x:result.localizationResult.x2,y:result.localizationResult.y2},
        {x:result.localizationResult.x3,y:result.localizationResult.y3},
        {x:result.localizationResult.x4,y:result.localizationResult.y4}
      ];
      analysingResults.push(analysingResult)
    }
    return analysingResults;
  }

  continuousChange(event:any){
    this.continuous = event.target.checked;
  }
}

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  camera-preview {
    height:100%;
    width:100%;
    position: absolute;
    right:0;
    top:0;
  }

  #close-btn {
    position:absolute;
    right:0;
    top:0;
  }
</style>

<div>
  <div [ngStyle]="{'display':active ? 'none':''}">
    <button (click)="startCamera()">Start Camera</button>
    <input (change)="continuousChange($event)" name="continuous" value="continuous" type="checkbox" /> 
    <label>Continuous Scan</label>
  </div>
  <camera-preview 
    ngModel #cameraElement
    desired-camera="founder"
    draw-overlay="true"
    (opened)="onOpened()" 
    [active]="active"
    [ngStyle]="{'display':active ? '':'none'}"
  >
    <button id="close-btn" (click)="stopCamera()">Close</button>
  </camera-preview>
</div>

// vue/barcode-scanner/src/App.vue
<script setup lang="ts">
  import { onMounted, ref } from 'vue';
  import { BarcodeReader, type TextResult } from "dynamsoft-javascript-barcode";

  BarcodeReader.engineResourcePath = "https://unpkg.com/dynamsoft-javascript-barcode@9.0.2/dist/";
  let reader:BarcodeReader;
  let scanned = false;
  let decoding = false;
  let interval:any = null;
  const continuous = ref(false);
  const cameraElement:any = ref(null);
  const active = ref(false);

  onMounted(async () => {
    BarcodeReader.license = "DLS2eyJoYW5kc2hha2VDb2RlIjoiMjAwMDAxLTE2NDk4Mjk3OTI2MzUiLCJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSIsInNlc3Npb25QYXNzd29yZCI6IndTcGR6Vm05WDJrcEQ5YUoifQ==";
    reader = await BarcodeReader.createInstance();
  })

  const startCamera = () => {
    active.value  = true;
  }

  const stopCamera = () => {
    active.value  = false;
  }

  const onOpened = () => {
    console.log("opened");
    startDecoding();
  }

  const startDecoding = () => {
    scanned = false;
    stopDecoding();
    //1000/25=40
    interval = setInterval(decode, 40);
  }

  const stopDecoding = () => {
    clearInterval(interval);
  }

  const decode = async () => {
    if (decoding === false && reader && cameraElement.value) {
      console.log("decoding");
      const video = await cameraElement.value.getVideoElement();
      decoding = true;
      try {
        let results = await reader.decode(video);
        if (results.length>0 && scanned === false && continuous.value === false) {
          scanned = true;
          stopDecoding();
          stopCamera();
          alert(results[0].barcodeText);
        }else{
          await cameraElement.value.updateAnalysingResults(wrapResults(results));
        }

      } catch (error) {
        console.log(error);
      }
      decoding = false;
    }
  }

  const wrapResults = (results:TextResult[]) => {
    let analysingResults = [];
    for (let index = 0; index < results.length; index++) {
      const result = results[index];
      let analysingResult:any = {};
      analysingResult.text = result.barcodeText;
      analysingResult.localizationResult = [
        {x:result.localizationResult.x1,y:result.localizationResult.y1},
        {x:result.localizationResult.x2,y:result.localizationResult.y2},
        {x:result.localizationResult.x3,y:result.localizationResult.y3},
        {x:result.localizationResult.x4,y:result.localizationResult.y4}
      ];
      analysingResults.push(analysingResult)
    }
    return analysingResults;
  }
</script>

<template>
  <div :style="{display: active ? 'none' : '' }">
    <button v-on:click="startCamera">Start Camera</button>
    <label>
    <input type="checkbox" v-model="continuous" />
    Continuous Scan
    </label>
  </div>
  <camera-preview 
    ref="cameraElement"
    desired-camera="founder"
    draw-overlay="true"
    v-on:opened="onOpened"
    :active="active"
    :style="{display: active ? '' : 'none' }"
  >
    <button id="close-btn" v-on:click="stopCamera">Close</button>
  </camera-preview>
</template>

<style>
  camera-preview {
    height:100%;
    width:100%;
    position: absolute;
    right:0;
    top:0;
  }

  #close-btn {
    position:absolute;
    right:0;
    top:0;
  }
</style>
